name: "delete-all"
version: "0.1.0"
usage: "delete all releases from all namespaces"
description: "Use to delete all releases from all namespaces. simply type helm delete-all"
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/delete-all.sh"
# platformCommand:
#   - os: linux
#     arch: i386
#     command: "$HELM_PLUGIN_DIR/delete-all.sh"
#   - os: linux
#     arch: amd64
#     command: "$HELM_PLUGIN_DIR/delete-all.sh"
#   - os: windows
#     arch: amd64
#     command: "$HELM_PLUGIN_DIR/delete-all.sh"